apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drupal
    type: backend
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
      type: backend
  template:
    metadata:
      labels:
        app: drupal
        type: backend
    spec:
      containers:
      - image: drupal:8.6
        name: drupal-container
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secrets
                key: root-password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secrets
                key: database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secrets
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secrets
                key: password
