apiVersion: v1
kind: Service
metadata:
  labels:
    app: drupal
    type: backend
  name: drupal-service
spec:
  ports:
  - nodePort: 30095
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: drupal
    type: backend
  type: NodePort
