apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx-phpfpm
spec:
  containers:
  - image: php:8.2-fpm-alpine
    name: php-fpm-container
    volumeMounts: 
    - name: shared-files
      mountPath: /var/www/html
  - image: nginx:latest
    name: nginx-container
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: shared-files
    emptyDir: {}
  - name: nginx-config-volume
    configMap:
      name: nginx-config
