apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-service
spec:
  ports:
  - nodePort: 30012
    port: 8097
    protocol: TCP
    targetPort: 8097
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
