apiVersion: v1
kind: Pod
metadata:
  labels:
    app: devops
  name: secret-devops
spec:
  containers:
  - image: centos:latest
    name: secret-container-devops
    volumeMounts:
    - name: secret-volume
      mountPath: "/opt/games"
    command: ["sleep", "infinity"]
  volumes:
  - name: secret-volume
    secret:
      secretName: beta
