apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nautilus
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  storageClassName: manual
  hostPath:
    path: /mnt/itadmin
