apiVersion: v1
kind: Service
metadata:
  labels:
    app: nautilus
  name: web-nautilus
spec:
  ports:
  - nodePort: 30008
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nautilus
  type: NodePort
