apiVersion: v1
kind: Service
metadata:
  labels:
    type: backend
  name: mysql-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: lamp
    role: mysql
  type: ClusterIP
