apiVersion: v1
data:
  MYSQL_DATABASE: bGFtcGRi
  MYSQL_HOST: bXlzcWwtc2VydmljZQ==
  MYSQL_PASSWORD: bWpvbG5pcjEyMw==
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_USER: dGhvcg==
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-config
