apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd
  name: httpd-service-xfusion
  namespace: httpd-namespace-xfusion
spec:
  ports:
  - nodePort: 30004
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpd
  type: NodePort
