apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-app
  name: grafana-deployment-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
      - image: grafana/grafana
        name: grafana-container
        ports:
        - containerPort: 3000
