apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-app
  name: grafana-service
spec:
  ports:
  - nodePort: 32000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana-app
  type: NodePort
status:
  loadBalancer: {}
