apiVersion: v1
kind: Pod
metadata:
  labels:
    run: envars
  name: envars
spec:
  containers:
  - image: httpd:latest
    name: fieldref-container
    env:
    - name: NODE_NAME
      valueFrom: 
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom: 
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom: 
        fieldRef: 
          fieldPath: status.podIP
    - name: POD_SERVICE_ACCOUNT
      valueFrom: 
        fieldRef:
          fieldPath: spec.serviceAccountName
    command: ["sh", "-c"]
    args:
    - while true; do
      echo -en '\n';
      printenv NODE_NAME POD_NAME POD_NAMESPACE;
      printenv POD_IP POD_SERVICE_ACCOUNT;
      sleep 10;
      done;
  restartPolicy: Always
