apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomcat
  name: tomcat-service-nautilus
  namespace: tomcat-namespace-nautilus
spec:
  ports:
  - nodePort: 32227
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcat
  type: NodePort
status:
  loadBalancer: {}
